import { User } from "@/domain/User/User";
import { IEventImage } from "@/domain/Event/IEventImage.interface";
import { IEventCategory } from "@/domain/Event/IEventCategory.interface";
import { Id, Timestamp } from "@/_core/Base.type";
import { IEventPlace } from "@/domain/Event/IEventPlace.interface";
import { IEventPhoto } from "@/domain/Event/IEventPhoto.interface";
import { IEventDto } from "@/domain/Event/IEventDto.interface";

export class Event {
  public readonly id: Id;
  public readonly createdAt: Timestamp;
  public readonly name: string;
  public readonly description: string;
  public readonly category: string;
  public readonly categoryID: Id;
  public readonly site: string;
  public readonly photos: IEventPhoto[];
  public readonly images: IEventImage[];
  public readonly tags: string[];
  public readonly ageRestriction: number;
  public readonly link: string;
  public readonly status: number;
  public readonly ratingCount: number;
  public readonly minPrice: number;
  public readonly maxPrice: number;
  public readonly author: User;
  public readonly rating: number;
  public readonly estimate: boolean;
  public readonly isFree: boolean;
  public readonly isOnline: boolean;
  public readonly detailURL: string;
  public readonly soldOut: boolean;
  public readonly similar: Event[];
  public readonly place: string;
  public readonly subscribedUserIds: Id[];
  public readonly subscribersCount: number;
  public readonly seance: IEventPlace;
  public readonly statusString: string;
  public readonly subscribedUser: User[];
  public readonly categories: IEventCategory[];
  public readonly since: number;
  public readonly till: number;
  public readonly checkPrice: boolean;
  public readonly cover: string;

  constructor(dto: IEventDto) {
    this.id = dto.id;
    this.createdAt = dto.createdAt;
    this.name = dto.name;
    this.description = dto.description;
    this.category = dto.category;
    this.categoryID = dto.categoryID;
    this.site = dto.site;
    this.photos = dto.photos;
    this.images = dto.images;
    this.tags = dto.tags;
    this.ageRestriction = dto.ageRestriction;
    this.link = dto.link;
    this.status = dto.status;
    this.ratingCount = dto.ratingCount;
    this.minPrice = dto.minPrice;
    this.maxPrice = dto.maxPrice;
    this.author = dto.author;
    this.rating = dto.rating;
    this.estimate = dto.estimate;
    this.isFree = dto.isFree;
    this.isOnline = dto.isOnline;
    this.detailURL = dto.detailURL;
    this.soldOut = dto.soldOut;
    this.similar = dto.similar;
    this.place = dto.place;
    this.subscribedUserIds = dto.subscribedUserIds;
    this.subscribersCount = dto.subscribersCount;
    this.seance = dto.seance;
    this.statusString = dto.statusString;
    this.subscribedUser = dto.subscribedUser;
    this.categories = dto.categories;
    this.since = dto.since;
    this.till = dto.till;
    this.checkPrice = dto.checkPrice;
    this.cover = dto.cover;
  }
}
