export enum ESearchContentType {
  NEWS = "news",
  USER = "user",
  HASHTAG = "hashtag",
  FEED = "feed",
  POST = "post",
  VIDEO = "video",
  CLIP = "clip",
  EVENT = "event",
  MUSIC = "music",
  ARTIST = "artist",
  TRACK = "track",
  ALBUM = "album",
  PLAYLIST = "playlist",
}
