export enum EActionContentType {
  AUDIO = "audio",
  VIDEO = "video",
  CLIP = "clip",
  POST = "post",
  NEWS = "news",
  FEED = "feed",
  EVENT = "event",
  COMMENT_POST = "commentPost",
  COMMENT_NEWS = "commentNews",
  COMMENT_VIDEO = "commentVideo",
  COMMENT_CLIP = "commentClip",
  REPLY_POST = "replyPost",
  REPLY_NEWS = "replyNews",
  REPLY_VIDEO = "replyVideo",
  REPLY_CLIP = "replyClip",
  USER = "user",
  USER_CONTENT = "userContent",
  HASHTAG = "hashtag",
  YARUS = "yarus",
  SEANCE = "seance",
}
