export enum EApiErrorCode {
  NOT_DETERMINED = "not_determined",
  VALIDATION_ERROR = "validation_error",
  CONTENT_HASHTAG_LIMIT = "CONTENT_HASHTAG_LIMIT",
  OTP_RETRY_LIMIT_EXCEEDED = "OTP_RETRY_LIMIT_EXCEEDED",
  CAPTCHA_WRONG_INPUT = "CAPTCHA_WRONG_INPUT",
  OTP_CHECK_INVALID_CODE = "OTP_CHECK_INVALID_CODE",
  OTP_TOO_MANY_REQUESTS = "OTP_TOO_MANY_REQUESTS",
}
